sudo: required


services:
  - docker

env:
  global:
    - PI_APP=clima-sensors
  matrix:
    - PI_TYPE=rpi3
    - PI_TYPE=zero

script: bash travis.sh


notifications:
   email:
      - mig.ruiz@gmail.com