FROM resin/raspberry-pi-debian
RUN [ "cross-build-start" ]

RUN apt-get update && \
apt-get install -yqq curl build-essential supervisor

#install node
RUN curl -o node-v8.11.3-linux-armv6l.tar.gz https://nodejs.org/dist/latest-v8.x/node-v8.11.3-linux-armv6l.tar.gz \
&& tar -xzf node-v8.11.3-linux-armv6l.tar.gz \
&& cp -R node-v8.11.3-linux-armv6l/* /usr/local/

RUN curl -o wiringpi.tar.gz  "https://git.drogon.net/?p=wiringPi;a=snapshot;h=8d188fa0e00bb8c6ff6eddd07bf92857e9bd533a;sf=tgz" \
&&  mkdir /wiringPi \
&& tar -xzf wiringpi.tar.gz  -C /wiringPi --strip-components=1 \
&& cd /wiringPi/ \
&& ./build \
&& cd ..


RUN mkdir /code/ && mkdir /code/pusher/ 

COPY pusher/package.json  /code/pusher/package.json

RUN cd /code/pusher \
&& npm  install 

COPY pusher /code/pusher

RUN mkdir /code/extractor/ 
COPY extractor /code/extractor

RUN cd /code/extractor \
&& make 


RUN mkdir /sensordata




ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN [ "cross-build-end" ]  





ENTRYPOINT ["/usr/bin/supervisord"]


