FROM resin/raspberry-pi-debian
RUN [ "cross-build-start" ]

#install node
RUN curl -o node-v8.11.3-linux-armv6l.tar.gz https://nodejs.org/dist/latest-v8.x/node-v8.11.3-linux-armv6l.tar.gz \
&& tar -xzf node-v8.11.3-linux-armv6l.tar.gz \
&& cp -R node-v8.11.3-linux-armv6l/* /usr/local/


RUN apt-get update && \
apt-get install -yqq --no-install-recommends g++ gcc make supervisor  && rm -rf /var/lib/apt/lists/*



RUN curl -o wiringpi.tar.gz  "https://git.drogon.net/?p=wiringPi;a=snapshot;h=8d188fa0e00bb8c6ff6eddd07bf92857e9bd533a;sf=tgz" \
&&  mkdir /wiringPi \
&& tar -xzf wiringpi.tar.gz  -C /wiringPi --strip-components=1 \
&& cd /wiringPi/ \
&& ./build \
&& cd ..

RUN mkdir /code/

RUN mkdir /code/extractor/ 
COPY extractor /code/extractor

RUN cd /code/extractor \
&& make 

RUN  mkdir /code/pusher/ 

COPY pusher/package.json  /code/pusher/package.json

RUN cd /code/pusher \
&& npm  install 




RUN mkdir /sensordata

COPY pusher /code/pusher


COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN [ "cross-build-end" ]  

ENV NODEID 2
ENV TEMPQUEUEURL amqp://pi:pi@192.168.0.96



ENTRYPOINT ["/usr/bin/supervisord"]


